### ISSUE TITLE
Support for customer error handling

### ISSUE THREAD

**Issue by timbogit** [textmaster/faraday_middleware-circuit_breaker#3]
The underlying stoplight gem support [custom error handling](https://github.com/orgsync/stoplight#custom-errors) via the `.with_error_handler` method.
It would be very useful for my use case to add an option to this Faraday middleware that allows for passing such a costum error handler, as it would be great to allow for particular error types to be exempt from tripping the circuit breaker (like regular `403` or `401` responses from downstream services, which aren't really out-of-the-ordinary conditions that should trip the breaker).

E.g., we have code elsewhere using stoplight that does something like this to exempt the `NON_TRIPPING` error classes from tripping the breaker:
```ruby
    Stoplight(name, &block)
      .with_threshold(MY_THRESHOLD)
      .with_error_handler do |error, handle|
        raise error if NON_TRIPPING_ERRORS.any? { |exempt_err| error.is_a?(exempt_err) }
        handle.call(error)
      end
     .run
```

This issue is a request to add an `error_handler` option with similar behavior to this middleware, where the default error handler would just be [`Stoplight::Default::ERROR_HANDLER`](https://github.com/orgsync/stoplight/blob/master/lib/stoplight/default.rb#L9)

**Comment by timbogit** [comment]
@gottfrois / @knapo : is this gem still maintained?
If so, are you accepting PRs for this issue?

**Comment by gottfrois** [comment]
hey @timbogit
Long time we haven't pushed anything to master but I'll gladly accept PRs!

**Comment by timbogit** [comment]
Thanks, @gottfrois !

I spun up #4 to add this feature.
Please let me know your feedback and - if deemed acceptable - if and when you could issue this gem version.

Thanks!
